title: Doreen He # your name (or website title) here
logo: "/images/profile.png?raw=true" # your photo (or logo) here
description: > # your text below (remove <br> elements if you don't need line breaks)
  
  <br>
  Hello, my name is Doreen. I'm currently a B.Sc Computer Science student at McGill University. I'm passionate about technologies in computer graphics and animations. My main technical skills include C++/C, Java, Python, OpenGL, and GLSLshaders. I also have experience in 3d modelling and designing in 3ds Max. Recently, I have been exploring various machine learning topics in practice. 
  <br>
  <br>
  Here are some of my projects XD! Click the projects to view more details and my source codes.
  <br>
  



  
theme: jekyll-theme-minimal

google_analytics: UA-000000-0 # your Google Analytics tracking ID here
